// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9JB5kuoe6Xwj8-vzN_BCY0uY7KwZc0q8',
    appId: '1:563959496641:web:956f7d9964c48823af3940',
    messagingSenderId: '563959496641',
    projectId: 'badada-efbb5',
    authDomain: 'badada-efbb5.firebaseapp.com',
    storageBucket: 'badada-efbb5.firebasestorage.app',
    measurementId: 'G-DE1TKWPCWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVQXDWpKu7vhXsBJKKiRs_QAETSgo4ptg',
    appId: '1:563959496641:android:72558ad602638cf6af3940',
    messagingSenderId: '563959496641',
    projectId: 'badada-efbb5',
    storageBucket: 'badada-efbb5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwlEmtAKpyuOy2YaqOQ0LT06iPmHTSpsk',
    appId: '1:563959496641:ios:c9b01ec52e769075af3940',
    messagingSenderId: '563959496641',
    projectId: 'badada-efbb5',
    storageBucket: 'badada-efbb5.firebasestorage.app',
    iosBundleId: 'com.example.badada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwlEmtAKpyuOy2YaqOQ0LT06iPmHTSpsk',
    appId: '1:563959496641:ios:c9b01ec52e769075af3940',
    messagingSenderId: '563959496641',
    projectId: 'badada-efbb5',
    storageBucket: 'badada-efbb5.firebasestorage.app',
    iosBundleId: 'com.example.badada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9JB5kuoe6Xwj8-vzN_BCY0uY7KwZc0q8',
    appId: '1:563959496641:web:503a7a483f34a733af3940',
    messagingSenderId: '563959496641',
    projectId: 'badada-efbb5',
    authDomain: 'badada-efbb5.firebaseapp.com',
    storageBucket: 'badada-efbb5.firebasestorage.app',
    measurementId: 'G-5MVYBYG0PS',
  );
}
